Test refactored custom CI actions
Changes not intended for merge to main.

diff --git a/.github/workflows/client.yml b/.github/workflows/client.yml
--- a/.github/workflows/client.yml
+++ b/.github/workflows/client.yml
@@ -43,242 +43,242 @@ jobs:
             path-filter:
               - './!((docs|infrastructure|scripts|staker-rewards)/**)'
 
-  client-build-test-publish-ethereum:
-    needs: client-detect-changes
-    if: |
-      github.event_name == 'push'
-        || github.event_name == 'schedule'
-        || needs.client-detect-changes.outputs.path-filter == 'true'
-        || (github.event_name == 'workflow_dispatch' 
-        && github.event.inputs.environment != 'alfajores')
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
+  # client-build-test-publish-ethereum:
+  #   needs: client-detect-changes
+  #   if: |
+  #     github.event_name == 'push'
+  #       || github.event_name == 'schedule'
+  #       || needs.client-detect-changes.outputs.path-filter == 'true'
+  #       || (github.event_name == 'workflow_dispatch' 
+  #       && github.event.inputs.environment != 'alfajores')
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Load environment variables
-        uses: keep-network/ci/actions/load-env-variables@v1
-        if: github.event_name == 'workflow_dispatch'
-        with:
-          environment: ${{ github.event.inputs.environment }}
+  #     - name: Load environment variables
+  #       uses: keep-network/ci/actions/load-env-variables@v1
+  #       if: github.event_name == 'workflow_dispatch'
+  #       with:
+  #         environment: ${{ github.event.inputs.environment }}
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
 
-      - name: Cache Docker layers
-        uses: actions/cache@v2
-        with:
-          path: /tmp/.buildx-ethereum-cache
-          key: ${{ runner.os }}-buildx-ethereum-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-ethereum-
+  #     - name: Cache Docker layers
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: /tmp/.buildx-ethereum-cache
+  #         key: ${{ runner.os }}-buildx-ethereum-${{ github.sha }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-buildx-ethereum-
 
-      - name: Build Docker Build Image
-        uses: docker/build-push-action@v2
-        with:
-          target: gobuild
-          tags: go-build-env-ethereum
-          load: true # load image to local registry to use it in next steps
-          cache-from: type=local,src=/tmp/.buildx-ethereum-cache
-          cache-to: type=local,dest=/tmp/.buildx-ethereum-cache-new
+  #     - name: Build Docker Build Image
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         target: gobuild
+  #         tags: go-build-env-ethereum
+  #         load: true # load image to local registry to use it in next steps
+  #         cache-from: type=local,src=/tmp/.buildx-ethereum-cache
+  #         cache-to: type=local,dest=/tmp/.buildx-ethereum-cache-new
 
-      - name: Run Go tests
-        run: |
-          docker run \
-            --workdir /go/src/github.com/keep-network/keep-ecdsa \
-            go-build-env-ethereum \
-            gotestsum
+  #     - name: Run Go tests
+  #       run: |
+  #         docker run \
+  #           --workdir /go/src/github.com/keep-network/keep-ecdsa \
+  #           go-build-env-ethereum \
+  #           gotestsum
 
-      - name: Build Docker Runtime Image
-        if: github.event_name != 'workflow_dispatch'
-        uses: docker/build-push-action@v2
-        env:
-          IMAGE_NAME: "keep-ecdsa-ethereum"
-        with:
-          labels: revision=${{ github.sha }}
-          build-args: |
-            REVISION=${{ github.sha }}
-          # VERSION= ? TODO: Configure version, sample: 1.7.6
-          push: false
+  #     - name: Build Docker Runtime Image
+  #       if: github.event_name != 'workflow_dispatch'
+  #       uses: docker/build-push-action@v2
+  #       env:
+  #         IMAGE_NAME: "keep-ecdsa-ethereum"
+  #       with:
+  #         labels: revision=${{ github.sha }}
+  #         build-args: |
+  #           REVISION=${{ github.sha }}
+  #         # VERSION= ? TODO: Configure version, sample: 1.7.6
+  #         push: false
 
-      - name: Login to Google Container Registry
-        if: github.event_name == 'workflow_dispatch'
-        uses: docker/login-action@v1
-        with:
-          registry: ${{ env.GCR_REGISTRY_URL }}
-          username: _json_key
-          password: ${{ secrets.KEEP_TEST_GCR_JSON_KEY }}
+  #     - name: Login to Google Container Registry
+  #       if: github.event_name == 'workflow_dispatch'
+  #       uses: docker/login-action@v1
+  #       with:
+  #         registry: ${{ env.GCR_REGISTRY_URL }}
+  #         username: _json_key
+  #         password: ${{ secrets.KEEP_TEST_GCR_JSON_KEY }}
 
-      - name: Build and publish Docker Runtime Image
-        if: github.event_name == 'workflow_dispatch'
-        uses: docker/build-push-action@v2
-        env:
-          IMAGE_NAME: "keep-ecdsa-ethereum"
-        with:
-          # GCR image should be named according to following convention:
-          # HOSTNAME/PROJECT-ID/IMAGE:TAG
-          # We don't use TAG yet, will be added at later stages of work on RFC-18.
-          tags: ${{ env.GCR_REGISTRY_URL }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}
-          labels: revision=${{ github.sha }}
-          build-args: |
-            REVISION=${{ github.sha }}
-          # VERSION= ? TODO: Configure version, sample: 1.7.6
-          push: true
+  #     - name: Build and publish Docker Runtime Image
+  #       if: github.event_name == 'workflow_dispatch'
+  #       uses: docker/build-push-action@v2
+  #       env:
+  #         IMAGE_NAME: "keep-ecdsa-ethereum"
+  #       with:
+  #         # GCR image should be named according to following convention:
+  #         # HOSTNAME/PROJECT-ID/IMAGE:TAG
+  #         # We don't use TAG yet, will be added at later stages of work on RFC-18.
+  #         tags: ${{ env.GCR_REGISTRY_URL }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}
+  #         labels: revision=${{ github.sha }}
+  #         build-args: |
+  #           REVISION=${{ github.sha }}
+  #         # VERSION= ? TODO: Configure version, sample: 1.7.6
+  #         push: true
 
-      - name: Notify CI about completion of the workflow
-        if: github.event_name == 'workflow_dispatch'
-        uses: keep-network/ci/actions/notify-workflow-completed@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-        with:
-          module: "github.com/keep-network/keep-ecdsa"
-          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-          environment: ${{ github.event.inputs.environment }}
-          upstream_builds: ${{ github.event.inputs.upstream_builds }}
-          upstream_ref: ${{ github.event.inputs.upstream_ref }}
-          version: ${{ github.sha }} # TODO: replace with version once versioning ready
+  #     - name: Notify CI about completion of the workflow
+  #       if: github.event_name == 'workflow_dispatch'
+  #       uses: keep-network/ci/actions/notify-workflow-completed@v1
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+  #       with:
+  #         module: "github.com/keep-network/keep-ecdsa"
+  #         url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #         environment: ${{ github.event.inputs.environment }}
+  #         upstream_builds: ${{ github.event.inputs.upstream_builds }}
+  #         upstream_ref: ${{ github.event.inputs.upstream_ref }}
+  #         version: ${{ github.sha }} # TODO: replace with version once versioning ready
 
-      - # Temp fix - move cache instead of copying (added below step and
-        # modified value of `cache-to`).
-        # https://github.com/docker/build-push-action/issues/252
-        # https://github.com/moby/buildkit/issues/1896
-        # Without the change some jobs were failing with `no space left on device`
-        name: Move cache
-        run: |
-          rm -rf /tmp/.buildx-ethereum-cache
-          mv /tmp/.buildx-ethereum-cache-new /tmp/.buildx-ethereum-cache
+  #     - # Temp fix - move cache instead of copying (added below step and
+  #       # modified value of `cache-to`).
+  #       # https://github.com/docker/build-push-action/issues/252
+  #       # https://github.com/moby/buildkit/issues/1896
+  #       # Without the change some jobs were failing with `no space left on device`
+  #       name: Move cache
+  #       run: |
+  #         rm -rf /tmp/.buildx-ethereum-cache
+  #         mv /tmp/.buildx-ethereum-cache-new /tmp/.buildx-ethereum-cache
 
-  client-build-test-publish-celo:
-    needs: client-detect-changes
-    if: |
-      github.event_name == 'push'
-        || github.event_name == 'schedule'
-        || needs.client-detect-changes.outputs.path-filter == 'true'
-        || (github.event_name == 'workflow_dispatch' 
-        && github.event.inputs.environment == 'alfajores')
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
+  # client-build-test-publish-celo:
+  #   needs: client-detect-changes
+  #   if: |
+  #     github.event_name == 'push'
+  #       || github.event_name == 'schedule'
+  #       || needs.client-detect-changes.outputs.path-filter == 'true'
+  #       || (github.event_name == 'workflow_dispatch' 
+  #       && github.event.inputs.environment == 'alfajores')
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Load environment variables
-        uses: keep-network/ci/actions/load-env-variables@v1
-        if: github.event_name == 'workflow_dispatch'
-        with:
-          environment: ${{ github.event.inputs.environment }}
+  #     - name: Load environment variables
+  #       uses: keep-network/ci/actions/load-env-variables@v1
+  #       if: github.event_name == 'workflow_dispatch'
+  #       with:
+  #         environment: ${{ github.event.inputs.environment }}
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
 
-      - name: Cache Docker layers
-        uses: actions/cache@v2
-        with:
-          path: /tmp/.buildx-celo-cache
-          key: ${{ runner.os }}-buildx-celo-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-celo-
+  #     - name: Cache Docker layers
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: /tmp/.buildx-celo-cache
+  #         key: ${{ runner.os }}-buildx-celo-${{ github.sha }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-buildx-celo-
 
-      - name: Build Docker Build Image
-        uses: docker/build-push-action@v2
-        with:
-          target: gobuild
-          tags: go-build-env-celo
-          build-args: |
-            HOST_CHAIN=celo
-          load: true # load image to local registry to use it in next steps
-          cache-from: type=local,src=/tmp/.buildx-celo-cache
-          cache-to: type=local,dest=/tmp/.buildx-celo-cache-new
+  #     - name: Build Docker Build Image
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         target: gobuild
+  #         tags: go-build-env-celo
+  #         build-args: |
+  #           HOST_CHAIN=celo
+  #         load: true # load image to local registry to use it in next steps
+  #         cache-from: type=local,src=/tmp/.buildx-celo-cache
+  #         cache-to: type=local,dest=/tmp/.buildx-celo-cache-new
 
-      - name: Run Go tests
-        run: |
-          docker run \
-            --workdir /go/src/github.com/keep-network/keep-ecdsa \
-            go-build-env-celo \
-            gotestsum -- -tags=celo,musl ./...
+  #     - name: Run Go tests
+  #       run: |
+  #         docker run \
+  #           --workdir /go/src/github.com/keep-network/keep-ecdsa \
+  #           go-build-env-celo \
+  #           gotestsum -- -tags=celo,musl ./...
 
-      - name: Login to Google Container Registry
-        if: github.event_name == 'workflow_dispatch'
-        uses: docker/login-action@v1
-        with:
-          registry: ${{ env.GCR_REGISTRY_URL }}
-          username: _json_key
-          password: ${{ secrets.KEEP_TEST_GCR_JSON_KEY }}
+  #     - name: Login to Google Container Registry
+  #       if: github.event_name == 'workflow_dispatch'
+  #       uses: docker/login-action@v1
+  #       with:
+  #         registry: ${{ env.GCR_REGISTRY_URL }}
+  #         username: _json_key
+  #         password: ${{ secrets.KEEP_TEST_GCR_JSON_KEY }}
 
-      - name: Build Docker Runtime Image
-        if: github.event_name != 'workflow_dispatch'
-        uses: docker/build-push-action@v2
-        env:
-          IMAGE_NAME: "keep-ecdsa-celo"
-        with:
-          labels: revision=${{ github.sha }}
-          build-args: |
-            HOST_CHAIN=celo
-            REVISION=${{ github.sha }}
-          # VERSION= ? TODO: Configure version, sample: 1.7.6
-          push: false
+  #     - name: Build Docker Runtime Image
+  #       if: github.event_name != 'workflow_dispatch'
+  #       uses: docker/build-push-action@v2
+  #       env:
+  #         IMAGE_NAME: "keep-ecdsa-celo"
+  #       with:
+  #         labels: revision=${{ github.sha }}
+  #         build-args: |
+  #           HOST_CHAIN=celo
+  #           REVISION=${{ github.sha }}
+  #         # VERSION= ? TODO: Configure version, sample: 1.7.6
+  #         push: false
 
-      - name: Build and publish Docker Runtime Image
-        if: github.event_name == 'workflow_dispatch'
-        uses: docker/build-push-action@v2
-        env:
-          IMAGE_NAME: "keep-ecdsa-celo"
-        with:
-          # GCR image should be named according to following convention:
-          # HOSTNAME/PROJECT-ID/IMAGE:TAG
-          # We don't use TAG yet, will be added at later stages of work on RFC-18.
-          tags: ${{ env.GCR_REGISTRY_URL }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}
-          labels: revision=${{ github.sha }}
-          build-args: |
-            HOST_CHAIN=celo
-            REVISION=${{ github.sha }}
-          # VERSION= ? TODO: Configure version, sample: 1.7.6
-          push: true
+  #     - name: Build and publish Docker Runtime Image
+  #       if: github.event_name == 'workflow_dispatch'
+  #       uses: docker/build-push-action@v2
+  #       env:
+  #         IMAGE_NAME: "keep-ecdsa-celo"
+  #       with:
+  #         # GCR image should be named according to following convention:
+  #         # HOSTNAME/PROJECT-ID/IMAGE:TAG
+  #         # We don't use TAG yet, will be added at later stages of work on RFC-18.
+  #         tags: ${{ env.GCR_REGISTRY_URL }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}
+  #         labels: revision=${{ github.sha }}
+  #         build-args: |
+  #           HOST_CHAIN=celo
+  #           REVISION=${{ github.sha }}
+  #         # VERSION= ? TODO: Configure version, sample: 1.7.6
+  #         push: true
 
-      - # Temp fix - move cache instead of copying (added below step and
-        # modified value of `cache-to`).
-        # https://github.com/docker/build-push-action/issues/252
-        # https://github.com/moby/buildkit/issues/1896
-        # Without the change some jobs were failing with `no space left on device`
-        name: Move cache
-        run: |
-          rm -rf /tmp/.buildx-celo-cache
-          mv /tmp/.buildx-celo-cache-new /tmp/.buildx-celo-cache
+  #     - # Temp fix - move cache instead of copying (added below step and
+  #       # modified value of `cache-to`).
+  #       # https://github.com/docker/build-push-action/issues/252
+  #       # https://github.com/moby/buildkit/issues/1896
+  #       # Without the change some jobs were failing with `no space left on device`
+  #       name: Move cache
+  #       run: |
+  #         rm -rf /tmp/.buildx-celo-cache
+  #         mv /tmp/.buildx-celo-cache-new /tmp/.buildx-celo-cache
 
-      - name: Notify CI about completion of the workflow
-        if: github.event_name == 'workflow_dispatch'
-        uses: keep-network/ci/actions/notify-workflow-completed@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-        with:
-          module: "github.com/keep-network/keep-ecdsa"
-          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-          environment: ${{ github.event.inputs.environment }}
-          upstream_builds: ${{ github.event.inputs.upstream_builds }}
-          upstream_ref: ${{ github.event.inputs.upstream_ref }}
-          version: ${{ github.sha }} # TODO: replace with version once versioning ready
+  #     - name: Notify CI about completion of the workflow
+  #       if: github.event_name == 'workflow_dispatch'
+  #       uses: keep-network/ci/actions/notify-workflow-completed@v1
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+  #       with:
+  #         module: "github.com/keep-network/keep-ecdsa"
+  #         url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #         environment: ${{ github.event.inputs.environment }}
+  #         upstream_builds: ${{ github.event.inputs.upstream_builds }}
+  #         upstream_ref: ${{ github.event.inputs.upstream_ref }}
+  #         version: ${{ github.sha }} # TODO: replace with version once versioning ready
 
-  client-lint:
-    needs: client-detect-changes
-    if: |
-      github.event_name == 'push'
-        || needs.client-detect-changes.outputs.path-filter == 'true'
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
+  # client-lint:
+  #   needs: client-detect-changes
+  #   if: |
+  #     github.event_name == 'push'
+  #       || needs.client-detect-changes.outputs.path-filter == 'true'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Lint Go
-        uses: keep-network/golint-action@v1.0.2
+  #     - name: Lint Go
+  #       uses: keep-network/golint-action@v1.0.2
 
-  client-scan:
-    needs: client-detect-changes
-    if: |
-      github.event_name == 'push'
-        || needs.client-detect-changes.outputs.path-filter == 'true'
-    runs-on: ubuntu-latest
-    env:
-      GO111MODULE: on
-    steps:
-      - uses: actions/checkout@v2
-      - uses: securego/gosec@master
-        with:
-          args: |
-            -exclude-dir=pkg/chain/gen
-            ./...
+  # client-scan:
+  #   needs: client-detect-changes
+  #   if: |
+  #     github.event_name == 'push'
+  #       || needs.client-detect-changes.outputs.path-filter == 'true'
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     GO111MODULE: on
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: securego/gosec@master
+  #       with:
+  #         args: |
+  #           -exclude-dir=pkg/chain/gen
+  #           ./...
